# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 625f5e0af0e6f07a08cc96ef2cdcca21e49123fd8877cf1065f22e56e07080be9f04769bed44081ea5afd6d22f93fdf56851d83689aaaae272fc3caaa0caff47

test:
  secret_key_base: 6c583b760379570fdf30c19c5b8402634214b572c12b7868183ab95ab79840a3b345f5be684f6341781e4da7df3fc64401c0959ca987abe9953dd8332fe856d8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
